# Generated by Django 2.2.10 on 2021-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalleReunion', models.CharField(max_length=150)),
                ('Transport', models.CharField(max_length=150)),
                ('Nouriture', models.CharField(max_length=150)),
            ],
        ),
    ]
