# Generated by Django 3.2.4 on 2021-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule', models.CharField(max_length=150)),
                ('Nom', models.CharField(max_length=150)),
                ('Prenom', models.CharField(max_length=150)),
                ('Num_teleph', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Domaine', models.CharField(max_length=150)),
                ('Grade', models.CharField(max_length=150)),
                ('Annee_expertise', models.CharField(max_length=150)),
                ('Etablissement', models.CharField(max_length=150)),
            ],
        ),
    ]
