# Generated by Django 2.2.10 on 2021-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule', models.CharField(max_length=150)),
                ('Nom', models.CharField(max_length=150)),
                ('Prenom', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Domaine', models.CharField(max_length=150)),
            ],
        ),
    ]
